In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({'label': ['A', 'B', 'C', 'A', 'B', 'C'], 'value': [1, 2, 3, 4, 5, 6]})
df

  label  value
0     A      1
1     B      2
2     C      3
3     A      4
4     B      5
5     C      6

In [5]:
df['label']

0    A
1    B
2    C
3    A
4    B
5    C
Name: label, dtype: object

In [6]:
df.loc[2]

label    C
value    3
Name: 2, dtype: object

In [9]:
df['label'].str.lower()

0    a
1    b
2    c
3    a
4    b
5    c
Name: label, dtype: object

In [14]:
s0 = pd.Series([0, 10, 20, 30, 40])
s1 = pd.Series([0, 10, 20, 30, 40], index=['A', 'A', 'B', 'C', 'D'])
print(s0, s1)

0     0
1    10
2    20
3    30
4    40
dtype: int64 A     0
A    10
B    20
C    30
D    40
dtype: int64

In [18]:
s1[2], s1['B'], s1.iloc[2], s1.loc['B']

(20, 20, 20, 20)

In [27]:
s1[2:4]

B    20
C    30
dtype: int64

In [30]:
s1.iloc[2:4]

B    20
C    30
dtype: int64

In [33]:
pd.date_range('26-10-2020', periods=7)

DatetimeIndex(['2020-10-26', '2020-10-27', '2020-10-28', '2020-10-29',
               '2020-10-30', '2020-10-31', '2020-11-01'],
              dtype='datetime64[ns]', freq='D')

In [71]:
alunos = pd.DataFrame({
    'nome': ['Ana', 'Rui', 'Gil', 'Zé', 'Tó'], 
    'idade': [20, 25, 27, 23, 20], 
    'presencas': [20, 3, 28, 17, 28], 
    'notaIA': [12.2, 5.3, 15.7, 15.9, 19.2]})
alunos

  nome  idade  presencas  notaIA
0  Ana     20         20    12.2
1  Rui     25          3     5.3
2  Gil     27         28    15.7
3   Zé     23         17    15.9
4   Tó     20         28    19.2

In [35]:
data = [['Ana', 20, 20 ,12.2], ['Rui', 25, 3, 5.3], ['Gil', 27, 28, 15.7], ['Zé', 23, 17, 15.9], ['Tó', 20, 28, 19.2]]
labels = ['nome', 'idada', 'presencas', 'notaIA']
pd.DataFrame(data, columns=labels)

  nome  idada  presencas  notaIA
0  Ana     20         20    12.2
1  Rui     25          3     5.3
2  Gil     27         28    15.7
3   Zé     23         17    15.9
4   Tó     20         28    19.2

In [72]:
alunos.index = [32134, 33333, 40000, 44444, 30000]

In [ ]:
pd.read_csv('dados.csv')

In [47]:
alunos.values

array([['Ana', 20, 20, 12.2],
       ['Rui', 25, 3, 5.3],
       ['Gil', 27, 28, 15.7],
       ['Zé', 23, 17, 15.9],
       ['Tó', 20, 28, 19.2]], dtype=object)

In [73]:
alunos.head(2)

      nome  idade  presencas  notaIA
32134  Ana     20         20    12.2
33333  Rui     25          3     5.3

In [74]:
alunos.tail(2)

      nome  idade  presencas  notaIA
44444   Zé     23         17    15.9
30000   Tó     20         28    19.2

In [75]:
alunos.describe()

           idade  presencas     notaIA
count   5.000000   5.000000   5.000000
mean   23.000000  19.200000  13.660000
std     3.082207  10.281051   5.288951
min    20.000000   3.000000   5.300000
25%    20.000000  17.000000  12.200000
50%    23.000000  20.000000  15.700000
75%    25.000000  28.000000  15.900000
max    27.000000  28.000000  19.200000

In [51]:
alunos[['nome', 'idade']]

      nome  idade
32134  Ana     20
33333  Rui     25
40000  Gil     27
44444   Zé     23
30000   Tó     20

In [52]:
alunos.idade

32134    20
33333    25
40000    27
44444    23
30000    20
Name: idade, dtype: int64

loc  -> usa como indice o respectivo rótulo  
iloc -> usa como indice a posição relativa

In [76]:
alunos.iloc[1:3, :]

      nome  idade  presencas  notaIA
33333  Rui     25          3     5.3
40000  Gil     27         28    15.7

In [54]:
alunos.iloc[:, 0:2]

      nome  idade
32134  Ana     20
33333  Rui     25
40000  Gil     27
44444   Zé     23
30000   Tó     20

In [77]:
alunos.iloc[1:3, 2:]

       presencas  notaIA
33333          3     5.3
40000         28    15.7

In [78]:
alunos[(alunos.presencas < 25) & (alunos.idade > 20)]

      nome  idade  presencas  notaIA
33333  Rui     25          3     5.3
44444   Zé     23         17    15.9

In [79]:
alunos.at[40000, 'notaIA']

15.7

In [80]:
alunos.sort_index(axis=0) #inplace para alterar tabela original

      nome  idade  presencas  notaIA
30000   Tó     20         28    19.2
32134  Ana     20         20    12.2
33333  Rui     25          3     5.3
40000  Gil     27         28    15.7
44444   Zé     23         17    15.9

In [81]:
alunos.sort_index(axis=1)

       idade nome  notaIA  presencas
32134     20  Ana    12.2         20
33333     25  Rui     5.3          3
40000     27  Gil    15.7         28
44444     23   Zé    15.9         17
30000     20   Tó    19.2         28

In [83]:
alunos.sort_values('notaIA', ascending=False)

      nome  idade  presencas  notaIA
30000   Tó     20         28    19.2
44444   Zé     23         17    15.9
40000  Gil     27         28    15.7
32134  Ana     20         20    12.2
33333  Rui     25          3     5.3

In [84]:
anonimos = alunos.iloc[:, 1:]
anonimos.sort_values(33333, axis=1)

       presencas  notaIA  idade
32134         20    12.2     20
33333          3     5.3     25
40000         28    15.7     27
44444         17    15.9     23
30000         28    19.2     20

In [86]:
alunos.notaIA.apply(round) #apply(round, args=(1,))

32134    12
33333     5
40000    16
44444    16
30000    19
Name: notaIA, dtype: int64

In [87]:
alunos.presencas.apply(lambda x: x ** 2)

32134    400
33333      9
40000    784
44444    289
30000    784
Name: presencas, dtype: int64

In [90]:
alunos['freqAnt'] = [False, False, True, False, True]
alunos

      nome  idade  presencas  notaIA  freqAnt
32134  Ana     20         20    12.2    False
33333  Rui     25          3     5.3    False
40000  Gil     27         28    15.7     True
44444   Zé     23         17    15.9    False
30000   Tó     20         28    19.2     True